language: cpp
sudo: enabled
install:
- curl https://raw.githubusercontent.com/Southclaws/sampctl/master/install-deb.sh | sh
- sudo dpkg --add-architecture i386
- sudo apt update && sudo apt install -y g++-multilib
- travis_wait pip install scipy
- travis_wait pip install pysam
- pip install .
script:
- sampctl package ensure
- sampctl package build
- sampctl package run